### ISSUE TITLE
Rust and Cargo versions

### ISSUE THREAD

**Issue by Juici** [KamranMackey/Ellie#151]
When you retrieve the Rust and Cargo versions for the [help command](https://github.com/KamranMackey/Ellie/blob/rust_rewrite/src/commands/utils/version.rs), you should not expect the machine running your bot to have rust or cargo installed.

What you appear you after is the version of Rust and Cargo that the bot was compiled against.

The best way to get the versions of Rust and Cargo at compile time would be to write a [build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html).

One method would be to output compile time environment variables for the `env!` macro to use, this can be found under [this section](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script) of the docs.

**Comment by KamranMackey** [comment]
@Juici thanks for the suggestions, however I do not know my way around the Cargo build script system. If you'd be willing to help me out, or create a pull request that integrates the functionality, it would be really helpful. Thanks :)
