### ISSUE TITLE
Move away from dotenv in favor of a TOML configuration file

### ISSUE THREAD

**Issue by KamranMackey** [KamranMackey/Ellie#155]
Ellie currently uses a generic dotenv configuration. It would be best if we moved this over to a TOML configuration file, to allow for better configuration file organization.

**Comment by sonro** [comment]
Hi, I would be interested in tackling this. Due to the way serenity is used it seems the easiest option would be to use a global `CONFIG` variable - perhaps using [lazy_static](https://github.com/rust-lang-nursery/lazy-static.rs).

**Comment by KamranMackey** [comment]
@sonro That sounds like a good idea. If you're interested in helping me tackle this, it would indeed mean a lot!
